version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - blog-net

  backend:
    image: blogagg:0.0.2
    container_name: blog-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:mypassword@my-postgres/mydatabase?sslmode=disable
    ports:
      - "8080:8080"
    networks:
      - blog-net

  # 可选：前端开发时可暴露前端端口

volumes:
  postgres-data: {}

networks:
  blog-net: {}
